library(tidyverse)
library(formatR)
library(dplyr)
library(ggplot2)
library(gganimate)
library(transformr)

# Set directory and retrieve stored data sets generated by "project1codeFinal - GIF FUN"
setwd("~/ST502/Projects/Project1/gif")
load("binom95CI.RData")

# Create plot GIF for Interval Length
lineLength <- ggplot(data=plotLength,aes(x=p,y=value,color=Method))
lineLength +
  geom_line(size=1) +
  scale_y_continuous(breaks = c(0,.2,.4,.6,.8,1), limits = c(0,1)) +
  labs(x="p",y="Average Interval Length") +
  theme_bw()+
  # gganimate code below
  ggtitle("Interval Length @ n: {frame_time}") +
    # n was my sample size column
  transition_time(n) +
  ease_aes("linear") +
  enter_fade() +
  exit_fade()

# Save as a GIF
# animate(lineLength, fps = 5, width = 750, height = 450) # Could not get this to work
anim_save("length_nTo200.gif")

# Create GIF for Proportion Contained
# Use data=subset(plotContain,Method=="") to plot specific methods
# Use data=subset(plotContain,n==) to plot specific n
lineContain <- ggplot(data=plotContain,aes(x=p,y=value,color=Method))
lineContain <- lineContain +
  geom_line(size=1) +
  scale_y_continuous(breaks = c(0,.2,.4,.6,.8,.95), limits = c(0,1)) +
  facet_wrap(vars(Method),labeller = label_both) +
  labs(x="p",y="Proportion Contained") +
  theme_bw() +
  # gganimate code below
  ggtitle("Proportion Contained @ n: {frame_time}") +
  transition_time(n) + # Generates frame_time var used in ggtitle()
  ease_aes("linear") +
  enter_fade() +
  exit_fade()

# Adjust GIF properties and save object to current working directory
# https://www.rdocumentation.org/packages/gganimate/versions/1.0.7/topics/animate
animate(lineContain,width=960,height=540,nframes = 200) # 960x540 is a 16:9 frame ratio
anim_save("contained_nTo200.gif")

# duration
# nframes = 100

# You can use the options width and height to set the dimensions, in pixels, of the animation;
# fps sets the frame rate, in frames per second, for a GIF.
